FROM jsturtevant/fluentd AS base


FROM mcr.microsoft.com/windows/servercore:ltsc2019

COPY --from=base ["C:\\opt\\td-agent", "C:\\opt\\td-agent"]

COPY fluent.conf /fluent/conf/fluent.conf
COPY custom/ /fluent/config/custom/

#RUN  C:/opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-cloudwatch-logs


ENTRYPOINT ["cmd", "/k", "C:\\opt\\td-agent\\embedded\\bin\\fluentd", "-c", "C:\\fluent\\conf\\fluent.conf"]