apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-server-iis
  namespace: amazon-cloudwatch
spec:
  selector:
    matchLabels:
      app: windows-server-iis
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: windows-server-iis
        tier: backend
        track: stable
    spec:
      containers:
      - name: log-gen
        image: vijayashankar/loggen-windows:ltsc2019
        env:
        - name: runforever
          value: "true"
        imagePullPolicy: IfNotPresent
      nodeSelector:
        beta.kubernetes.io/os: windows