---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: windows-prod
  region: us-west-2
  version: '1.14'

managedNodeGroups:
  - name: linux-ng
    instanceType: t2.large
    minSize: 1
nodeGroups:
  - name: windows-ng
    instanceType: t2.large
    minSize: 1
    volumeSize: 100
    amiFamily: WindowsServer2019FullContainer
    ami: ami-0518d02190e88fecf