---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: windows-prod-1903
  region: us-west-2
  version: '1.14'

managedNodeGroups:
  - name: linux-ng
    instanceType: t2.large
    minSize: 1

nodeGroups:
  - name: windows-ng
    instanceType: m5.large
    minSize: 2
    volumeSize: 100
    ami: ami-0518d02190e88fecf
    amiFamily: WindowsServer2019FullContainer